[package]
name = "monkey_lang_bin"
version = "0.1.0"
authors = ["tuna"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monkey_lang_lib = {path = '../monkey_lang_lib'}